// Generated by the protocol buffer compiler.  DO NOT EDIT!

package ch.neiva.watchedepisodes.servlets.protocols;

public final class SearchSeriesProtocol {
  private SearchSeriesProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SearchSeriesResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SearchSeriesResponse.newBuilder() to construct.
    private SearchSeriesResponse() {}
    
    private static final SearchSeriesResponse defaultInstance = new SearchSeriesResponse();
    public static SearchSeriesResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchSeriesResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.internal_static_SearchSeriesResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.internal_static_SearchSeriesResponse_fieldAccessorTable;
    }
    
    // repeated .PBSeriesSummary series = 1;
    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary> series_ =
      java.util.Collections.emptyList();
    public java.util.List<ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary> getSeriesList() {
      return series_;
    }
    public int getSeriesCount() { return series_.size(); }
    public ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary getSeries(int index) {
      return series_.get(index);
    }
    
    public final boolean isInitialized() {
      for (ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary element : getSeriesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary element : getSeriesList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary element : getSeriesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse result;
      
      // Construct using watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse();
        return builder;
      }
      
      protected ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse.getDescriptor();
      }
      
      public ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse getDefaultInstanceForType() {
        return ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.series_ != java.util.Collections.EMPTY_LIST) {
          result.series_ =
            java.util.Collections.unmodifiableList(result.series_);
        }
        ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse) {
          return mergeFrom((ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse other) {
        if (other == ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse.getDefaultInstance()) return this;
        if (!other.series_.isEmpty()) {
          if (result.series_.isEmpty()) {
            result.series_ = new java.util.ArrayList<ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary>();
          }
          result.series_.addAll(other.series_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary.Builder subBuilder = ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSeries(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .PBSeriesSummary series = 1;
      public java.util.List<ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary> getSeriesList() {
        return java.util.Collections.unmodifiableList(result.series_);
      }
      public int getSeriesCount() {
        return result.getSeriesCount();
      }
      public ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary getSeries(int index) {
        return result.getSeries(index);
      }
      public Builder setSeries(int index, ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.series_.set(index, value);
        return this;
      }
      public Builder setSeries(int index, ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary.Builder builderForValue) {
        result.series_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSeries(ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary>();
        }
        result.series_.add(value);
        return this;
      }
      public Builder addSeries(ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary.Builder builderForValue) {
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary>();
        }
        result.series_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSeries(
          java.lang.Iterable<? extends ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary> values) {
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.PBSeriesSummary>();
        }
        super.addAll(values, result.series_);
        return this;
      }
      public Builder clearSeries() {
        result.series_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.getDescriptor();
    }
    
    static {
      ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchSeriesResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SearchSeriesResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023search_series.proto\032\024protocol_types.pr" +
      "oto\"8\n\024SearchSeriesResponse\022 \n\006series\030\001 " +
      "\003(\0132\020.PBSeriesSummaryB:\n\"watchedepisodes" +
      ".servlets.protocolsB\024SearchSeriesProtoco" +
      "l"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SearchSeriesResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SearchSeriesResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SearchSeriesResponse_descriptor,
              new java.lang.String[] { "Series", },
              ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse.class,
              ch.neiva.watchedepisodes.servlets.protocols.SearchSeriesProtocol.SearchSeriesResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ch.neiva.watchedepisodes.servlets.protocols.ProtocolTypes.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
