// Generated by the protocol buffer compiler.  DO NOT EDIT!

public final class SearchResultsProtocol {
  private SearchResultsProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PBSearchResults extends
      com.google.protobuf.GeneratedMessage {
    // Use PBSearchResults.newBuilder() to construct.
    private PBSearchResults() {}
    
    private static final PBSearchResults defaultInstance = new PBSearchResults();
    public static PBSearchResults getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBSearchResults getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchResultsProtocol.internal_static_PBSearchResults_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchResultsProtocol.internal_static_PBSearchResults_fieldAccessorTable;
    }
    
    public static final class PBSeries extends
        com.google.protobuf.GeneratedMessage {
      // Use PBSeries.newBuilder() to construct.
      private PBSeries() {}
      
      private static final PBSeries defaultInstance = new PBSeries();
      public static PBSeries getDefaultInstance() {
        return defaultInstance;
      }
      
      public PBSeries getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchResultsProtocol.internal_static_PBSearchResults_PBSeries_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchResultsProtocol.internal_static_PBSearchResults_PBSeries_fieldAccessorTable;
      }
      
      // required string id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private boolean hasId;
      private java.lang.String id_ = "";
      public boolean hasId() { return hasId; }
      public java.lang.String getId() { return id_; }
      
      // required string name = 2;
      public static final int NAME_FIELD_NUMBER = 2;
      private boolean hasName;
      private java.lang.String name_ = "";
      public boolean hasName() { return hasName; }
      public java.lang.String getName() { return name_; }
      
      public final boolean isInitialized() {
        if (!hasId) return false;
        if (!hasName) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasId()) {
          output.writeString(1, getId());
        }
        if (hasName()) {
          output.writeString(2, getName());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasId()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getId());
        }
        if (hasName()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getName());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static SearchResultsProtocol.PBSearchResults.PBSeries parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(SearchResultsProtocol.PBSearchResults.PBSeries prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private SearchResultsProtocol.PBSearchResults.PBSeries result;
        
        // Construct using SearchResultsProtocol.PBSearchResults.PBSeries.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new SearchResultsProtocol.PBSearchResults.PBSeries();
          return builder;
        }
        
        protected SearchResultsProtocol.PBSearchResults.PBSeries internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new SearchResultsProtocol.PBSearchResults.PBSeries();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SearchResultsProtocol.PBSearchResults.PBSeries.getDescriptor();
        }
        
        public SearchResultsProtocol.PBSearchResults.PBSeries getDefaultInstanceForType() {
          return SearchResultsProtocol.PBSearchResults.PBSeries.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public SearchResultsProtocol.PBSearchResults.PBSeries build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private SearchResultsProtocol.PBSearchResults.PBSeries buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public SearchResultsProtocol.PBSearchResults.PBSeries buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          SearchResultsProtocol.PBSearchResults.PBSeries returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof SearchResultsProtocol.PBSearchResults.PBSeries) {
            return mergeFrom((SearchResultsProtocol.PBSearchResults.PBSeries)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(SearchResultsProtocol.PBSearchResults.PBSeries other) {
          if (other == SearchResultsProtocol.PBSearchResults.PBSeries.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasName()) {
            setName(other.getName());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setId(input.readString());
                break;
              }
              case 18: {
                setName(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string id = 1;
        public boolean hasId() {
          return result.hasId();
        }
        public java.lang.String getId() {
          return result.getId();
        }
        public Builder setId(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasId = true;
          result.id_ = value;
          return this;
        }
        public Builder clearId() {
          result.hasId = false;
          result.id_ = getDefaultInstance().getId();
          return this;
        }
        
        // required string name = 2;
        public boolean hasName() {
          return result.hasName();
        }
        public java.lang.String getName() {
          return result.getName();
        }
        public Builder setName(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
          result.name_ = value;
          return this;
        }
        public Builder clearName() {
          result.hasName = false;
          result.name_ = getDefaultInstance().getName();
          return this;
        }
      }
      
      static {
        SearchResultsProtocol.getDescriptor();
      }
      
      static {
        SearchResultsProtocol.internalForceInit();
      }
    }
    
    // repeated .PBSearchResults.PBSeries searchResult = 1;
    public static final int SEARCHRESULT_FIELD_NUMBER = 1;
    private java.util.List<SearchResultsProtocol.PBSearchResults.PBSeries> searchResult_ =
      java.util.Collections.emptyList();
    public java.util.List<SearchResultsProtocol.PBSearchResults.PBSeries> getSearchResultList() {
      return searchResult_;
    }
    public int getSearchResultCount() { return searchResult_.size(); }
    public SearchResultsProtocol.PBSearchResults.PBSeries getSearchResult(int index) {
      return searchResult_.get(index);
    }
    
    public final boolean isInitialized() {
      for (SearchResultsProtocol.PBSearchResults.PBSeries element : getSearchResultList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (SearchResultsProtocol.PBSearchResults.PBSeries element : getSearchResultList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (SearchResultsProtocol.PBSearchResults.PBSeries element : getSearchResultList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static SearchResultsProtocol.PBSearchResults parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static SearchResultsProtocol.PBSearchResults parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SearchResultsProtocol.PBSearchResults prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private SearchResultsProtocol.PBSearchResults result;
      
      // Construct using SearchResultsProtocol.PBSearchResults.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new SearchResultsProtocol.PBSearchResults();
        return builder;
      }
      
      protected SearchResultsProtocol.PBSearchResults internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new SearchResultsProtocol.PBSearchResults();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchResultsProtocol.PBSearchResults.getDescriptor();
      }
      
      public SearchResultsProtocol.PBSearchResults getDefaultInstanceForType() {
        return SearchResultsProtocol.PBSearchResults.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public SearchResultsProtocol.PBSearchResults build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private SearchResultsProtocol.PBSearchResults buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public SearchResultsProtocol.PBSearchResults buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.searchResult_ != java.util.Collections.EMPTY_LIST) {
          result.searchResult_ =
            java.util.Collections.unmodifiableList(result.searchResult_);
        }
        SearchResultsProtocol.PBSearchResults returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SearchResultsProtocol.PBSearchResults) {
          return mergeFrom((SearchResultsProtocol.PBSearchResults)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(SearchResultsProtocol.PBSearchResults other) {
        if (other == SearchResultsProtocol.PBSearchResults.getDefaultInstance()) return this;
        if (!other.searchResult_.isEmpty()) {
          if (result.searchResult_.isEmpty()) {
            result.searchResult_ = new java.util.ArrayList<SearchResultsProtocol.PBSearchResults.PBSeries>();
          }
          result.searchResult_.addAll(other.searchResult_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              SearchResultsProtocol.PBSearchResults.PBSeries.Builder subBuilder = SearchResultsProtocol.PBSearchResults.PBSeries.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSearchResult(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .PBSearchResults.PBSeries searchResult = 1;
      public java.util.List<SearchResultsProtocol.PBSearchResults.PBSeries> getSearchResultList() {
        return java.util.Collections.unmodifiableList(result.searchResult_);
      }
      public int getSearchResultCount() {
        return result.getSearchResultCount();
      }
      public SearchResultsProtocol.PBSearchResults.PBSeries getSearchResult(int index) {
        return result.getSearchResult(index);
      }
      public Builder setSearchResult(int index, SearchResultsProtocol.PBSearchResults.PBSeries value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.searchResult_.set(index, value);
        return this;
      }
      public Builder setSearchResult(int index, SearchResultsProtocol.PBSearchResults.PBSeries.Builder builderForValue) {
        result.searchResult_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSearchResult(SearchResultsProtocol.PBSearchResults.PBSeries value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.searchResult_.isEmpty()) {
          result.searchResult_ = new java.util.ArrayList<SearchResultsProtocol.PBSearchResults.PBSeries>();
        }
        result.searchResult_.add(value);
        return this;
      }
      public Builder addSearchResult(SearchResultsProtocol.PBSearchResults.PBSeries.Builder builderForValue) {
        if (result.searchResult_.isEmpty()) {
          result.searchResult_ = new java.util.ArrayList<SearchResultsProtocol.PBSearchResults.PBSeries>();
        }
        result.searchResult_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSearchResult(
          java.lang.Iterable<? extends SearchResultsProtocol.PBSearchResults.PBSeries> values) {
        if (result.searchResult_.isEmpty()) {
          result.searchResult_ = new java.util.ArrayList<SearchResultsProtocol.PBSearchResults.PBSeries>();
        }
        super.addAll(values, result.searchResult_);
        return this;
      }
      public Builder clearSearchResult() {
        result.searchResult_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      SearchResultsProtocol.getDescriptor();
    }
    
    static {
      SearchResultsProtocol.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBSearchResults_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBSearchResults_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBSearchResults_PBSeries_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBSearchResults_PBSeries_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035search_results_protocol.proto\"h\n\017PBSea" +
      "rchResults\022/\n\014searchResult\030\001 \003(\0132\031.PBSea" +
      "rchResults.PBSeries\032$\n\010PBSeries\022\n\n\002id\030\001 " +
      "\002(\t\022\014\n\004name\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PBSearchResults_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PBSearchResults_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBSearchResults_descriptor,
              new java.lang.String[] { "SearchResult", },
              SearchResultsProtocol.PBSearchResults.class,
              SearchResultsProtocol.PBSearchResults.Builder.class);
          internal_static_PBSearchResults_PBSeries_descriptor =
            internal_static_PBSearchResults_descriptor.getNestedTypes().get(0);
          internal_static_PBSearchResults_PBSeries_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBSearchResults_PBSeries_descriptor,
              new java.lang.String[] { "Id", "Name", },
              SearchResultsProtocol.PBSearchResults.PBSeries.class,
              SearchResultsProtocol.PBSearchResults.PBSeries.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
