// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class PBSearchResults;
@class PBSearchResults_Builder;
@class PBSearchResults_PBSeries;
@class PBSearchResults_PBSeries_Builder;

@interface SearchResultsProtocolRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PBSearchResults : PBGeneratedMessage {
@private
  NSMutableArray* mutableSearchResultList;
}
- (NSArray*) searchResultList;
- (PBSearchResults_PBSeries*) searchResultAtIndex:(int32_t) index;

+ (PBSearchResults*) defaultInstance;
- (PBSearchResults*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBSearchResults_Builder*) builder;
+ (PBSearchResults_Builder*) builder;
+ (PBSearchResults_Builder*) builderWithPrototype:(PBSearchResults*) prototype;

+ (PBSearchResults*) parseFromData:(NSData*) data;
+ (PBSearchResults*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBSearchResults*) parseFromInputStream:(NSInputStream*) input;
+ (PBSearchResults*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBSearchResults*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBSearchResults*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBSearchResults_PBSeries : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  NSString* id;
  NSString* name;
}
- (BOOL) hasId;
- (BOOL) hasName;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* name;

+ (PBSearchResults_PBSeries*) defaultInstance;
- (PBSearchResults_PBSeries*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBSearchResults_PBSeries_Builder*) builder;
+ (PBSearchResults_PBSeries_Builder*) builder;
+ (PBSearchResults_PBSeries_Builder*) builderWithPrototype:(PBSearchResults_PBSeries*) prototype;

+ (PBSearchResults_PBSeries*) parseFromData:(NSData*) data;
+ (PBSearchResults_PBSeries*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBSearchResults_PBSeries*) parseFromInputStream:(NSInputStream*) input;
+ (PBSearchResults_PBSeries*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBSearchResults_PBSeries*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBSearchResults_PBSeries*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBSearchResults_PBSeries_Builder : PBGeneratedMessage_Builder {
@private
  PBSearchResults_PBSeries* result;
}

- (PBSearchResults_PBSeries*) defaultInstance;

- (PBSearchResults_PBSeries_Builder*) clear;
- (PBSearchResults_PBSeries_Builder*) clone;

- (PBSearchResults_PBSeries*) build;
- (PBSearchResults_PBSeries*) buildPartial;

- (PBSearchResults_PBSeries_Builder*) mergeFrom:(PBSearchResults_PBSeries*) other;
- (PBSearchResults_PBSeries_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBSearchResults_PBSeries_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (PBSearchResults_PBSeries_Builder*) setId:(NSString*) value;
- (PBSearchResults_PBSeries_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (PBSearchResults_PBSeries_Builder*) setName:(NSString*) value;
- (PBSearchResults_PBSeries_Builder*) clearName;
@end

@interface PBSearchResults_Builder : PBGeneratedMessage_Builder {
@private
  PBSearchResults* result;
}

- (PBSearchResults*) defaultInstance;

- (PBSearchResults_Builder*) clear;
- (PBSearchResults_Builder*) clone;

- (PBSearchResults*) build;
- (PBSearchResults*) buildPartial;

- (PBSearchResults_Builder*) mergeFrom:(PBSearchResults*) other;
- (PBSearchResults_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBSearchResults_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) searchResultList;
- (PBSearchResults_PBSeries*) searchResultAtIndex:(int32_t) index;
- (PBSearchResults_Builder*) replaceSearchResultAtIndex:(int32_t) index with:(PBSearchResults_PBSeries*) value;
- (PBSearchResults_Builder*) addSearchResult:(PBSearchResults_PBSeries*) value;
- (PBSearchResults_Builder*) addAllSearchResult:(NSArray*) values;
- (PBSearchResults_Builder*) clearSearchResultList;
@end

