// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "SearchResultsProtocol.pb.h"

@implementation SearchResultsProtocolRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [SearchResultsProtocolRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PBSearchResults ()
@property (retain) NSMutableArray* mutableSearchResultList;
@end

@implementation PBSearchResults

@synthesize mutableSearchResultList;
- (void) dealloc {
  self.mutableSearchResultList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static PBSearchResults* defaultPBSearchResultsInstance = nil;
+ (void) initialize {
  if (self == [PBSearchResults class]) {
    defaultPBSearchResultsInstance = [[PBSearchResults alloc] init];
  }
}
+ (PBSearchResults*) defaultInstance {
  return defaultPBSearchResultsInstance;
}
- (PBSearchResults*) defaultInstance {
  return defaultPBSearchResultsInstance;
}
- (NSArray*) searchResultList {
  return mutableSearchResultList;
}
- (PBSearchResults_PBSeries*) searchResultAtIndex:(int32_t) index {
  id value = [mutableSearchResultList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  for (PBSearchResults_PBSeries* element in self.searchResultList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (PBSearchResults_PBSeries* element in self.searchResultList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (PBSearchResults_PBSeries* element in self.searchResultList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (PBSearchResults*) parseFromData:(NSData*) data {
  return (PBSearchResults*)[[[PBSearchResults builder] mergeFromData:data] build];
}
+ (PBSearchResults*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBSearchResults*)[[[PBSearchResults builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PBSearchResults*) parseFromInputStream:(NSInputStream*) input {
  return (PBSearchResults*)[[[PBSearchResults builder] mergeFromInputStream:input] build];
}
+ (PBSearchResults*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBSearchResults*)[[[PBSearchResults builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PBSearchResults*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PBSearchResults*)[[[PBSearchResults builder] mergeFromCodedInputStream:input] build];
}
+ (PBSearchResults*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBSearchResults*)[[[PBSearchResults builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PBSearchResults_Builder*) builder {
  return [[[PBSearchResults_Builder alloc] init] autorelease];
}
+ (PBSearchResults_Builder*) builderWithPrototype:(PBSearchResults*) prototype {
  return [[PBSearchResults builder] mergeFrom:prototype];
}
- (PBSearchResults_Builder*) builder {
  return [PBSearchResults builder];
}
@end

@interface PBSearchResults_PBSeries ()
@property (retain) NSString* id;
@property (retain) NSString* name;
@end

@implementation PBSearchResults_PBSeries

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value {
  hasId_ = !!value;
}
@synthesize id;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (void) dealloc {
  self.id = nil;
  self.name = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.name = @"";
  }
  return self;
}
static PBSearchResults_PBSeries* defaultPBSearchResults_PBSeriesInstance = nil;
+ (void) initialize {
  if (self == [PBSearchResults_PBSeries class]) {
    defaultPBSearchResults_PBSeriesInstance = [[PBSearchResults_PBSeries alloc] init];
  }
}
+ (PBSearchResults_PBSeries*) defaultInstance {
  return defaultPBSearchResults_PBSeriesInstance;
}
- (PBSearchResults_PBSeries*) defaultInstance {
  return defaultPBSearchResults_PBSeriesInstance;
}
- (BOOL) isInitialized {
  if (!self.hasId) {
    return NO;
  }
  if (!self.hasName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasName) {
    [output writeString:2 value:self.name];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasName) {
    size += computeStringSize(2, self.name);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (PBSearchResults_PBSeries*) parseFromData:(NSData*) data {
  return (PBSearchResults_PBSeries*)[[[PBSearchResults_PBSeries builder] mergeFromData:data] build];
}
+ (PBSearchResults_PBSeries*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBSearchResults_PBSeries*)[[[PBSearchResults_PBSeries builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PBSearchResults_PBSeries*) parseFromInputStream:(NSInputStream*) input {
  return (PBSearchResults_PBSeries*)[[[PBSearchResults_PBSeries builder] mergeFromInputStream:input] build];
}
+ (PBSearchResults_PBSeries*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBSearchResults_PBSeries*)[[[PBSearchResults_PBSeries builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PBSearchResults_PBSeries*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PBSearchResults_PBSeries*)[[[PBSearchResults_PBSeries builder] mergeFromCodedInputStream:input] build];
}
+ (PBSearchResults_PBSeries*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBSearchResults_PBSeries*)[[[PBSearchResults_PBSeries builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PBSearchResults_PBSeries_Builder*) builder {
  return [[[PBSearchResults_PBSeries_Builder alloc] init] autorelease];
}
+ (PBSearchResults_PBSeries_Builder*) builderWithPrototype:(PBSearchResults_PBSeries*) prototype {
  return [[PBSearchResults_PBSeries builder] mergeFrom:prototype];
}
- (PBSearchResults_PBSeries_Builder*) builder {
  return [PBSearchResults_PBSeries builder];
}
@end

@interface PBSearchResults_PBSeries_Builder()
@property (retain) PBSearchResults_PBSeries* result;
@end

@implementation PBSearchResults_PBSeries_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PBSearchResults_PBSeries alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PBSearchResults_PBSeries_Builder*) clear {
  self.result = [[[PBSearchResults_PBSeries alloc] init] autorelease];
  return self;
}
- (PBSearchResults_PBSeries_Builder*) clone {
  return [PBSearchResults_PBSeries builderWithPrototype:result];
}
- (PBSearchResults_PBSeries*) defaultInstance {
  return [PBSearchResults_PBSeries defaultInstance];
}
- (PBSearchResults_PBSeries*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PBSearchResults_PBSeries*) buildPartial {
  PBSearchResults_PBSeries* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PBSearchResults_PBSeries_Builder*) mergeFrom:(PBSearchResults_PBSeries*) other {
  if (other == [PBSearchResults_PBSeries defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PBSearchResults_PBSeries_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PBSearchResults_PBSeries_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (NSString*) id {
  return result.id;
}
- (PBSearchResults_PBSeries_Builder*) setId:(NSString*) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (PBSearchResults_PBSeries_Builder*) clearId {
  result.hasId = NO;
  result.id = @"";
  return self;
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (PBSearchResults_PBSeries_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (PBSearchResults_PBSeries_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
@end

@interface PBSearchResults_Builder()
@property (retain) PBSearchResults* result;
@end

@implementation PBSearchResults_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PBSearchResults alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PBSearchResults_Builder*) clear {
  self.result = [[[PBSearchResults alloc] init] autorelease];
  return self;
}
- (PBSearchResults_Builder*) clone {
  return [PBSearchResults builderWithPrototype:result];
}
- (PBSearchResults*) defaultInstance {
  return [PBSearchResults defaultInstance];
}
- (PBSearchResults*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PBSearchResults*) buildPartial {
  PBSearchResults* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PBSearchResults_Builder*) mergeFrom:(PBSearchResults*) other {
  if (other == [PBSearchResults defaultInstance]) {
    return self;
  }
  if (other.mutableSearchResultList.count > 0) {
    if (result.mutableSearchResultList == nil) {
      result.mutableSearchResultList = [NSMutableArray array];
    }
    [result.mutableSearchResultList addObjectsFromArray:other.mutableSearchResultList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PBSearchResults_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PBSearchResults_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        PBSearchResults_PBSeries_Builder* subBuilder = [PBSearchResults_PBSeries builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addSearchResult:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) searchResultList {
  if (result.mutableSearchResultList == nil) { return [NSArray array]; }
  return result.mutableSearchResultList;
}
- (PBSearchResults_PBSeries*) searchResultAtIndex:(int32_t) index {
  return [result searchResultAtIndex:index];
}
- (PBSearchResults_Builder*) replaceSearchResultAtIndex:(int32_t) index with:(PBSearchResults_PBSeries*) value {
  [result.mutableSearchResultList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (PBSearchResults_Builder*) addAllSearchResult:(NSArray*) values {
  if (result.mutableSearchResultList == nil) {
    result.mutableSearchResultList = [NSMutableArray array];
  }
  [result.mutableSearchResultList addObjectsFromArray:values];
  return self;
}
- (PBSearchResults_Builder*) clearSearchResultList {
  result.mutableSearchResultList = nil;
  return self;
}
- (PBSearchResults_Builder*) addSearchResult:(PBSearchResults_PBSeries*) value {
  if (result.mutableSearchResultList == nil) {
    result.mutableSearchResultList = [NSMutableArray array];
  }
  [result.mutableSearchResultList addObject:value];
  return self;
}
@end

