// Generated by the protocol buffer compiler.  DO NOT EDIT!

package watchedepisodes.servlets.protocols;

public final class GetAllEpisodesProtocol {
  private GetAllEpisodesProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026get_all_episodes.proto\032\024protocol_types" +
      ".protoB<\n\"watchedepisodes.servlets.proto" +
      "colsB\026GetAllEpisodesProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          watchedepisodes.servlets.protocols.ProtocolTypes.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
