// Generated by the protocol buffer compiler.  DO NOT EDIT!

package watchedepisodes.servlets.protocols;

public final class GetSeriesProtocol {
  private GetSeriesProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class GetSeriesResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use GetSeriesResponse.newBuilder() to construct.
    private GetSeriesResponse() {}
    
    private static final GetSeriesResponse defaultInstance = new GetSeriesResponse();
    public static GetSeriesResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public GetSeriesResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return watchedepisodes.servlets.protocols.GetSeriesProtocol.internal_static_GetSeriesResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return watchedepisodes.servlets.protocols.GetSeriesProtocol.internal_static_GetSeriesResponse_fieldAccessorTable;
    }
    
    // required .PBSeries series = 1;
    public static final int SERIES_FIELD_NUMBER = 1;
    private boolean hasSeries;
    private watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries series_ = watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries.getDefaultInstance();
    public boolean hasSeries() { return hasSeries; }
    public watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries getSeries() { return series_; }
    
    public final boolean isInitialized() {
      if (!hasSeries) return false;
      if (!getSeries().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasSeries()) {
        output.writeMessage(1, getSeries());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSeries()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSeries());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse result;
      
      // Construct using watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse();
        return builder;
      }
      
      protected watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse.getDescriptor();
      }
      
      public watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse getDefaultInstanceForType() {
        return watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse) {
          return mergeFrom((watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse other) {
        if (other == watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse.getDefaultInstance()) return this;
        if (other.hasSeries()) {
          mergeSeries(other.getSeries());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries.Builder subBuilder = watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries.newBuilder();
              if (hasSeries()) {
                subBuilder.mergeFrom(getSeries());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSeries(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .PBSeries series = 1;
      public boolean hasSeries() {
        return result.hasSeries();
      }
      public watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries getSeries() {
        return result.getSeries();
      }
      public Builder setSeries(watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSeries = true;
        result.series_ = value;
        return this;
      }
      public Builder setSeries(watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries.Builder builderForValue) {
        result.hasSeries = true;
        result.series_ = builderForValue.build();
        return this;
      }
      public Builder mergeSeries(watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries value) {
        if (result.hasSeries() &&
            result.series_ != watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries.getDefaultInstance()) {
          result.series_ =
            watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries.newBuilder(result.series_).mergeFrom(value).buildPartial();
        } else {
          result.series_ = value;
        }
        result.hasSeries = true;
        return this;
      }
      public Builder clearSeries() {
        result.hasSeries = false;
        result.series_ = watchedepisodes.servlets.protocols.ProtocolTypes.PBSeries.getDefaultInstance();
        return this;
      }
    }
    
    static {
      watchedepisodes.servlets.protocols.GetSeriesProtocol.getDescriptor();
    }
    
    static {
      watchedepisodes.servlets.protocols.GetSeriesProtocol.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSeriesResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetSeriesResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020get_series.proto\032\024protocol_types.proto" +
      "\".\n\021GetSeriesResponse\022\031\n\006series\030\001 \002(\0132\t." +
      "PBSeriesB7\n\"watchedepisodes.servlets.pro" +
      "tocolsB\021GetSeriesProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GetSeriesResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GetSeriesResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetSeriesResponse_descriptor,
              new java.lang.String[] { "Series", },
              watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse.class,
              watchedepisodes.servlets.protocols.GetSeriesProtocol.GetSeriesResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          watchedepisodes.servlets.protocols.ProtocolTypes.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
