// Generated by the protocol buffer compiler.  DO NOT EDIT!

package watchedepisodes.servlets.protocols;

public final class SearchSeriesProtocol {
  private SearchSeriesProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PBSearchResults extends
      com.google.protobuf.GeneratedMessage {
    // Use PBSearchResults.newBuilder() to construct.
    private PBSearchResults() {}
    
    private static final PBSearchResults defaultInstance = new PBSearchResults();
    public static PBSearchResults getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBSearchResults getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return watchedepisodes.servlets.protocols.SearchSeriesProtocol.internal_static_PBSearchResults_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return watchedepisodes.servlets.protocols.SearchSeriesProtocol.internal_static_PBSearchResults_fieldAccessorTable;
    }
    
    public static final class PBSeriesSummary extends
        com.google.protobuf.GeneratedMessage {
      // Use PBSeriesSummary.newBuilder() to construct.
      private PBSeriesSummary() {}
      
      private static final PBSeriesSummary defaultInstance = new PBSeriesSummary();
      public static PBSeriesSummary getDefaultInstance() {
        return defaultInstance;
      }
      
      public PBSeriesSummary getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return watchedepisodes.servlets.protocols.SearchSeriesProtocol.internal_static_PBSearchResults_PBSeriesSummary_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return watchedepisodes.servlets.protocols.SearchSeriesProtocol.internal_static_PBSearchResults_PBSeriesSummary_fieldAccessorTable;
      }
      
      // required string id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private boolean hasId;
      private java.lang.String id_ = "";
      public boolean hasId() { return hasId; }
      public java.lang.String getId() { return id_; }
      
      // required string name = 2;
      public static final int NAME_FIELD_NUMBER = 2;
      private boolean hasName;
      private java.lang.String name_ = "";
      public boolean hasName() { return hasName; }
      public java.lang.String getName() { return name_; }
      
      public final boolean isInitialized() {
        if (!hasId) return false;
        if (!hasName) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (hasId()) {
          output.writeString(1, getId());
        }
        if (hasName()) {
          output.writeString(2, getName());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasId()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getId());
        }
        if (hasName()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getName());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input).buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary result;
        
        // Construct using watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary();
          return builder;
        }
        
        protected watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.getDescriptor();
        }
        
        public watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary getDefaultInstanceForType() {
          return watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary) {
            return mergeFrom((watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary other) {
          if (other == watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasName()) {
            setName(other.getName());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setId(input.readString());
                break;
              }
              case 18: {
                setName(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string id = 1;
        public boolean hasId() {
          return result.hasId();
        }
        public java.lang.String getId() {
          return result.getId();
        }
        public Builder setId(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasId = true;
          result.id_ = value;
          return this;
        }
        public Builder clearId() {
          result.hasId = false;
          result.id_ = getDefaultInstance().getId();
          return this;
        }
        
        // required string name = 2;
        public boolean hasName() {
          return result.hasName();
        }
        public java.lang.String getName() {
          return result.getName();
        }
        public Builder setName(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
          result.name_ = value;
          return this;
        }
        public Builder clearName() {
          result.hasName = false;
          result.name_ = getDefaultInstance().getName();
          return this;
        }
      }
      
      static {
        watchedepisodes.servlets.protocols.SearchSeriesProtocol.getDescriptor();
      }
      
      static {
        watchedepisodes.servlets.protocols.SearchSeriesProtocol.internalForceInit();
      }
    }
    
    // repeated .PBSearchResults.PBSeriesSummary series = 1;
    public static final int SERIES_FIELD_NUMBER = 1;
    private java.util.List<watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary> series_ =
      java.util.Collections.emptyList();
    public java.util.List<watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary> getSeriesList() {
      return series_;
    }
    public int getSeriesCount() { return series_.size(); }
    public watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary getSeries(int index) {
      return series_.get(index);
    }
    
    public final boolean isInitialized() {
      for (watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary element : getSeriesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary element : getSeriesList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary element : getSeriesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults result;
      
      // Construct using watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults();
        return builder;
      }
      
      protected watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.getDescriptor();
      }
      
      public watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults getDefaultInstanceForType() {
        return watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.series_ != java.util.Collections.EMPTY_LIST) {
          result.series_ =
            java.util.Collections.unmodifiableList(result.series_);
        }
        watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults) {
          return mergeFrom((watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults other) {
        if (other == watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.getDefaultInstance()) return this;
        if (!other.series_.isEmpty()) {
          if (result.series_.isEmpty()) {
            result.series_ = new java.util.ArrayList<watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary>();
          }
          result.series_.addAll(other.series_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.Builder subBuilder = watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSeries(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .PBSearchResults.PBSeriesSummary series = 1;
      public java.util.List<watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary> getSeriesList() {
        return java.util.Collections.unmodifiableList(result.series_);
      }
      public int getSeriesCount() {
        return result.getSeriesCount();
      }
      public watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary getSeries(int index) {
        return result.getSeries(index);
      }
      public Builder setSeries(int index, watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.series_.set(index, value);
        return this;
      }
      public Builder setSeries(int index, watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.Builder builderForValue) {
        result.series_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSeries(watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary>();
        }
        result.series_.add(value);
        return this;
      }
      public Builder addSeries(watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.Builder builderForValue) {
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary>();
        }
        result.series_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSeries(
          java.lang.Iterable<? extends watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary> values) {
        if (result.series_.isEmpty()) {
          result.series_ = new java.util.ArrayList<watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary>();
        }
        super.addAll(values, result.series_);
        return this;
      }
      public Builder clearSeries() {
        result.series_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      watchedepisodes.servlets.protocols.SearchSeriesProtocol.getDescriptor();
    }
    
    static {
      watchedepisodes.servlets.protocols.SearchSeriesProtocol.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBSearchResults_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBSearchResults_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBSearchResults_PBSeriesSummary_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBSearchResults_PBSeriesSummary_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023search_series.proto\"p\n\017PBSearchResults" +
      "\0220\n\006series\030\001 \003(\0132 .PBSearchResults.PBSer" +
      "iesSummary\032+\n\017PBSeriesSummary\022\n\n\002id\030\001 \002(" +
      "\t\022\014\n\004name\030\002 \002(\tB:\n\"watchedepisodes.servl" +
      "ets.protocolsB\024SearchSeriesProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PBSearchResults_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PBSearchResults_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBSearchResults_descriptor,
              new java.lang.String[] { "Series", },
              watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.class,
              watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.Builder.class);
          internal_static_PBSearchResults_PBSeriesSummary_descriptor =
            internal_static_PBSearchResults_descriptor.getNestedTypes().get(0);
          internal_static_PBSearchResults_PBSeriesSummary_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBSearchResults_PBSeriesSummary_descriptor,
              new java.lang.String[] { "Id", "Name", },
              watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.class,
              watchedepisodes.servlets.protocols.SearchSeriesProtocol.PBSearchResults.PBSeriesSummary.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
